adjective = input('Введите прилагательное: ')
noun = input('Введите существительное: ')
verb = input('Введите глалол в прошедшем времени: ')
animal = input('Введите название животного: ')
print('Ваша чепуха: ')
print('Этот', adjective, noun, verb, 'на ленивый рыжий', animal)
